scalar Date

type User {
  id: ID!
  name: String!
  surname: String!
  email: String!
  password: String!
  status: Boolean!
  failed_attempts: Int!
  created_at: Date
  updated_at: Date
}

type Query {
  getAllUsers: [User]!
}

type Mutation {
  userAdd(id: ID!): User
}