# latest official node image
FROM node:10.15.3

MAINTAINER Enzo García <e.andres1997@gmail.com>

# RUN npm install --global nodemon
RUN npm install pm2@latest -g
RUN npm install --global sequelize sequelize-cli mysql2
RUN mkdir -p /usr/src

WORKDIR /usr/src

EXPOSE 3050

CMD ["bash", "./cm/init.sh"]
